name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Chạy mỗi 10 phút

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send request
        run: curl -s -o /dev/null "https://myapp-nop6.onrender.com/"
